### ISSUE TITLE
Dead links in README

### ISSUE THREAD

**Issue by GeorgeTailor** [sencha/ext-angular#178]
https://github.com/sencha/ext-angular/tree/master/packages/ext-angular-kitchensink - returns 404
https://examples.sencha.com/ExtAngular/6.7.0/kitchensink/ - returns 404

**Comment by mgusmano** [comment]
thanks for finding that - the first link is here

https://github.com/sencha/ext-angular/tree/ext-angular-6.7.x/packages/ext-angular-kitchensink

**Comment by mgusmano** [comment]
second is this:
https://examples.sencha.com/ExtAngular/6.7.0/kitchensink/

**Comment by mgusmano** [comment]
readme has been fixed
