### ISSUE TITLE
Getting started with angular cli

### ISSUE THREAD

**Issue by pesi-** [sencha/ext-angular#283]
Hello! 

I tried to get started with the getting_started.md document to integrate ext-angular within angular-cli. But unfortunately it didn't work.

First problem was, that the import in app.module.ts
`import { ExtAngularModernModule } from './ext-angular-modern/ext-angular-modern.module'`
is not possible because the folder doesn' exist and no @sencha/ext-angular-modern module was present. I changed that to 
`import { ExtAngularModule } from '@sencha/ext-angular'` in hope that this is the right one.
After that i got that build error: 

> Data path "" should NOT have additional properties(es5BrowserSupport).

Updating @angular-builders/custom-webpack and "@angular-builders/dev-server" to the latest version fixed that.

Now the build is successfull and a "dist" folder is created with ext-files in it, but the app doesnt work because the ext.js files are not hosted within the Angular dev server. Http-Error 404

![image](https://user-images.githubusercontent.com/8465587/54411731-5eea0080-46f0-11e9-896b-af2545bcdf1f.png)

I tried a few things but nothing worked.... 
Can you please try it yourself an update the readme and/or can you please help me?

THX in advance!

**Comment by akiroussama** [comment]
Hello Sencha Team,

 The same issue for me, any help please ?

Thanks in advance.

**Comment by deepakjha14** [comment]
same for me

**Comment by pesi-** [comment]
There is an early access version now ....
https://docs.sencha.com/extwebcomponents/7.0.0/guides/getting_started_vue.html

**Comment by mgusmano** [comment]
try this new doc:

https://github.com/sencha/ext-angular/blob/ext-angular-7.0.x/AngularCLI.md

**Comment by pesi-** [comment]
Thx. But this is for version 7.0.0. I don't have access yet. When will it be released? ext.js 7 is out today.

**Comment by mgusmano** [comment]
https://github.com/mgusmano/ext-angular/tree/ext-angular-7.1.x/packages/ext-angular
