### ISSUE TITLE
do you have plans to build ext-vue

### ISSUE THREAD

**Issue by jianchengwang** [sencha/ext-angular#285]
in china,there are much people and company use vue framework, also have some vue ui framework like element-ui,iview and so on，but in my opinion, i prefer extjs powerful gridview and unified style，so do u have plans to build etx-vue?

**Comment by pesi-** [comment]
As i know so far, they are planning to build WebComponents. 
https://developer.mozilla.org/en-US/docs/Web/Web_Components - a way to build independend components, that can be used with all diffrent kinds of frameworks out there.

**Comment by jianchengwang** [comment]
> As i know so far, they are planning to build WebComponents.
> https://developer.mozilla.org/en-US/docs/Web/Web_Components - a way to build independend components, that can be used with all diffrent kinds of frameworks out there.

sounds good, but maybe take a long time,

**Comment by pesi-** [comment]
There is an early access version for web-components now ....
https://docs.sencha.com/extwebcomponents/7.0.0/guides/getting_started_vue.html

**Comment by jianchengwang** [comment]
> There is an early access version for web-components now ....
> https://docs.sencha.com/extwebcomponents/7.0.0/guides/getting_started_vue.html

it's cool, i will try later, thx
