### ISSUE TITLE
Selector is hard coded in bootstrap module

### ISSUE THREAD

**Issue by branflake2267** [sencha/ext-angular#303]
The selector is hard coded in the bootstrap module. It's also declared in the app module. I would expect the app.module to declare it, would that be possible? 

https://github.com/sencha/ext-angular/blob/ext-angular-7.0.x/packages/ext-angular/src/lib/ext-angular-bootstrap.component.ts#L7 - app-root

**Comment by mgusmano** [comment]
solved
