### ISSUE TITLE
ExtAngular classic example doesn't work

### ISSUE THREAD

**Issue by gilbertoximenes** [sencha/ext-angular#457]
https://github.com/sencha/ext-angula...ING_STARTED.md

Throws: 'ExtColumn' is not a known element

If I change those tags to 'ExtGridcolumn' doesn't throws error but still shows a blank grid without columns.

If I set columns using setColumns() method, it shows the columns but setData() method doesn't work at all.

**Comment by mgusmano** [comment]
new getting started for 7.2

https://github.com/sencha/ext-angular/blob/ext-angular-7.2.x/packages/ext-angular-classic/guides/Creating_Angular_CLI_ExtAngular.md
