### ISSUE TITLE
Adding ExtAngularModern doesn't work

### ISSUE THREAD

**Issue by baenamkyu** [sencha/ext-angular#531]
![ext-angular-modern](https://user-images.githubusercontent.com/8123371/78779802-8933ed80-79d8-11ea-9a15-48b6aeb2d65b.jpg)

**Comment by mgusmano** [comment]
the docs for getting started have not been updated - in process now - here is the correct guide

https://github.com/sencha/ext-angular/blob/ext-angular-7.2.x/packages/ext-angular-modern/guides/Creating_Angular_CLI_ExtAngular.md

please confirm with me that this works
